### ISSUE TITLE
Tangerine (CA) bank not including transaction data (last transaction seen at unix epoch timestamp 1658145600)

### ISSUE THREAD

**Issue by d-allin** [simplefin/bridge-issues#4]
While — at time of writing — Simplefin Bridge shows the Last Sync Time of "Tangerine (CA)" as **2022-08-01 20:58:28**:
![image](https://user-images.githubusercontent.com/21145526/182251699-d63351e2-9f05-44be-b01c-b0336baebbbb.png)
... and `balance-date` reflects the time of the latest sync,  transactions are not being pulled by `GET` requests past `balance-date` 1658145600 (the last observed transaction in a Tangerine account).

For example, running a `/accounts?start-date=1658106000` returns (and `id` removed):
```
      {
         "org":{
            "domain":"www.tangerine.ca",
            "name":"Tangerine Bank (CA)",
            "sfin-url":"https://beta-bridge.simplefin.org/simplefin",
            "url":"http://www.tangerine.ca/en"
         },
         "id":"[removed]",
         "name":"Short Term Savings",
         "currency":"CAD",
         "balance":"11975.74",
         "available-balance":"0.00",
         "balance-date":1659387508,
         "transactions":[
            
         ]
      },
```

There are more Tangerine accounts returned but I think that's illustrative. The account(s) do have transactions and new balances they should be reporting.

The only transaction seen in a Tangerine account via `/accounts?start-date=1658106000` is:

```
      {
         "org":{
            "domain":"www.tangerine.ca",
            "name":"Tangerine Bank (CA)",
            "sfin-url":"https://beta-bridge.simplefin.org/simplefin",
            "url":"http://www.tangerine.ca/en"
         },
         "id":"[removed]",
         "name":"Tangerine Chequing Account",
         "currency":"CAD",
         "balance":"2684.15",
         "available-balance":"0.00",
         "balance-date":1659387508,
         "transactions":[
            {
               "id":"TRN-[removed]",
               "posted":1658145600,
               "amount":"1416.67",
               "description":"EFT Deposit from [removed]",
               "payee":"Deposit From [removed]",
               "memo":""
            }
         ]
      },
```
No subsequent transactions are seen on any of the Tangerine accounts.

**Comment by iffy** [comment]
I'm curious if you were to run the same query 24 hours later what the results would be. Also, I'm not sure what the timezone is for "Last Data Sync." I'll have to check on that.

**Comment by d-allin** [comment]
I'll give it a go after the 24-hour mark, but I should note that this has been an issue for several weeks.

Edit: I should also note that the original discovery of this issue was noticing that Tangerine (CA) transactions were not being updated in Buckets. The details in this bug submission were the result of me attempting to determine if the issue was with Simplefin Bridge or Buckets, so I could submit to the appropriate project.

**Comment by d-allin** [comment]
@iffy Ran it again to satisfy curiosity (though at the time you were unaware this had been happening for some time).

As for the past couple of weeks running the requests through Buckets, running it again w/ curl did not populate the transaction data.

![image](https://user-images.githubusercontent.com/21145526/182721215-a8cad573-576b-4703-a820-a990eb117b68.png)

While `balance` and `balance-date` are correctly reflected in the output, `transactions` continues to remain blank for any account where `domain` is www.tangerine.ca :

```
         "org":{
            "domain":"www.tangerine.ca",
            "name":"Tangerine Bank (CA)",
            "sfin-url":"https://beta-bridge.simplefin.org/simplefin",
            "url":"http://www.tangerine.ca/en"
         },
         "id":"removed",
         "name":"Tangerine World Mastercard",
         "currency":"CAD",
         "balance":"-59.72",
         "available-balance":"0.00",
         "balance-date":1659564547,
         "transactions":[
            
         ]
      },
```

**Comment by iffy** [comment]
@d-allin okay, then I think this is specific to your account. If you email info@simplefin.org from the email address you used to sign up, we'll file a ticket with the backend provider to get this fixed.

**Comment by d-allin** [comment]
I have sent the email to the address listed and will close this ticket (as it appears to not be a general issue).
