### ISSUE TITLE
Open Source or Self-host?

### ISSUE THREAD

**Issue by matt22207** [simplefin/bridge-issues#5]
Would you consider making the bridge open-source or allow local hosting? I would be happy to pay the license fee, but I'm not comfortable granting access to my banks on someone else's server. Thanks for consideration!

**Comment by iffy** [comment]
I understand not wanting to grant access to your banks, but at this time we don't offer a self-host option. Sorry

**Comment by matt22207** [comment]
Understood. Thanks!

**Comment by aadityabhatia** [comment]
Are you considering offering a self-hosting option sometime in the future? Will be fascinating to watch this project grow!

**Comment by iffy** [comment]
It won't really ever be possible to offer a self-hosting option because of the contracts we have with providers.
