### ISSUE TITLE
Discover card retriving transactions from last year, this month.

### ISSUE THREAD

**Issue by abnd90** [simplefin/bridge-issues#6]
I think I hit a bug in simplefin. Not sure if it is the bridge or simplefin. I have simplefin bridge connected to two clients, Actual budget and Buckets. My discover card is returning transactions from last march (march 2023) as those that happened this month (march 2024). This happens in both Actual budget and Buckets.

Happy to assist in whatever debugging necessary.

**Comment by iffy** [comment]
Sorry to hear that. Please sign in to the SimpleFIN Bridge and click "Report a problem" for that connection and we'll see what we can do.

Thanks!
