### ISSUE TITLE
Support "Authorization" header for access URLs

### ISSUE THREAD

**Issue by vivekagate** [simplefin/bridge-issues#7]
Currently, the access URLs are of the form:
https://username:password@beta-bridge.simplefin.org/simplefin

This URL does not work in browsers javascript fetch() calls due to this:
Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: https://<REACTED>:<REDACTED>@[beta-bridge.simplefin.org/simplefin](http://beta-bridge.simplefin.org/simplefin)

Can support be added where the username and password are sent as headers using Basic Authentication?

**Comment by iffy** [comment]
The Authorization header and Basic auth is already supported and how tools that support the username:password@ syntax in URLs do authentication.
