### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by mark-monteiro** [simplefin/bridge-issues#9]
Currently the only way to log into the site is with a login code that is sent to the registered email address. I would like the ability to secure my account with full two-factor authentication.

What this normally looks like is:

- 1st factor: A password
- 2nd factor: Short-lived one time code, generated via email, sms, authenticator app, etc

The current login via email is not ideal because the account is only protected by a single factor; if someone gains access to my email account they also have access to my SimpleFin Bridge account.

It is also pretty cumbersome to have to wait for the email, and open multiple tabs to log in. I would prefer to just enter a username, password and code to log in quickly.

**Comment by iffy** [comment]
Yes, sending a link via email is inconvenient. We also support signing in with a Passkey, which is much more convenient, if that works with your setup.

The SimpleFIN Bridge already supports 2FA using an authenticator app (scroll down on the My Account page). Once enabled, you will be required to enter it when doing sensitive actions such as creating a new app connection. It is also used as a second factor when signing in with a Passkey.

**Comment by mark-monteiro** [comment]
Oh that's great, I missed that there was support for passkeys. I'm using BitWarden to setting it up was super smooth and it works great.

Thanks for your help, this is resolved for me.
